---
apiVersion: v1
kind: Service
metadata:
  labels:
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: monitoring-grafana
  name: monitoring-grafana
  namespace: {{namespace}}
spec:
  type: {{svc_type}}
  ports:
    - port: 80
      targetPort: 3000
  selector:
    name: influxGrafana
