apiVersion: v1
kind: Secret
metadata:
  name: minio-user
  namespace: deis
  labels:
    heritage: deis
type: Opaque
data:
  access-key-id: {{storage_creds.minio.access_key | b64encode}}
  access-secret-key: {{storage_creds.minio.secret_key | b64encode}}
