#helm:generate helm template -o $HELM_GENERATE_DIR/manifests/deis-builder-secret-ssh-private-keys.yaml $HELM_GENERATE_DIR/tpl/deis-builder-secret-ssh-private-keys.yaml
apiVersion: v1
kind: Secret
metadata:
  name: builder-ssh-private-keys
  namespace: deis
  labels:
    heritage: deis
type: Opaque
data:
  ssh-host-rsa-key: "{{'rsa' | gen_privatekey | b64encode}}"
  ssh-host-dsa-key: "{{'dsa' | gen_privatekey| b64encode}}"
  ssh-host-ecdsa-key: "{{'ecdsa' | gen_privatekey | b64encode}}"
