#helm:generate helm tpl --out $HELM_GENERATE_DIR/manifests/deis-database-secret-creds.yaml $HELM_GENERATE_DIR/tpl/deis-database-secret-creds.yaml
apiVersion: v1
kind: Secret
metadata:
  name: database-creds
  namespace: deis
  labels:
    app: deis-database
    heritage: deis
data:
  user: {{ database_user | default(32 | rand_alphanum) | b64encode }}
  password: {{ database_password | default(32 | rand_alphanum) | b64encode }}
