---
apiVersion: v1
kind: ReplicationController
metadata:
  name: deis-database
  namespace: deis
  labels:
    heritage: deis
spec:
  replicas: 1
  selector:
    app: deis-database
  template:
    metadata:
      labels:
        app: deis-database
    spec:
      serviceAccount: deis-database
      containers:
        - name: deis-database
          image: {{database_image}}
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
          env:
            - name: DATABASE_STORAGE
              value: {{storage}}
          readinessProbe:
            exec:
              command:
                - is_running
            initialDelaySeconds: 30
            timeoutSeconds: 1
          volumeMounts:
            - name: database-creds
              mountPath: /var/run/secrets/deis/database/creds
            - name: objectstore-creds
              mountPath: /var/run/secrets/deis/objectstore/creds
      volumes:
        - name: database-creds
          secret:
            secretName: database-creds
        - name: objectstore-creds
          secret:
            secretName: objectstorage-keyfile
