apiVersion: v1
kind: Secret
metadata:
  name: objectstorage-keyfile
  namespace: deis
  labels:
    heritage: deis
  annotations:
    deis.io/objectstorage: "{{storage}}"
type: Opaque
data: {% if storage == "minio" %}
  accesskey: {{storage_creds.minio.access_key | b64encode}}
  secretkey: {{storage_creds.minio.secret_key | b64encode}}
  {% elif storage == "gcs" %}
  key.json: {{ storage_creds.gcs.key_json | b64encode }}
  registry-bucket: {{ registry_bucket | b64encode }}
  database-bucket: {{ database_bucket | b64encode }}
  builder-bucket:  {{ builder_bucket | b64encode }}
  {% elif storage == "azure" %}
  accountname: {{ storage_creds.azure.account_name | b64encode }}
  accountkey: {{ storage_creds.azure.account_key | b64encode }}
  registry-container: {{ registry_bucket | b64encode }}
  database-container: {{ database_bucket | b64encode }}
  builder-container:  {{ builder_bucket | b64encode }}
  {% elif storage == "s3" %}
  accesskey: {{ storage_creds.s3.access_key | b64encode }}
  secretkey: {{ storage_creds.s3.secret_key | b64encode }}
  region: {{ storage_creds.s3.region | b64encode }}
  registry-bucket: {{ registry_bucket | b64encode }}
  database-bucket: {{ database_bucket | b64encode }}
  builder-bucket:  {{ builder_bucket | b64encode }}
  {% endif %}
