---
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: kibana
  name: kibana

spec:
  type: {{svc_type}}
  ports:
    - port: 80
      targetPort: 5601
      name: kibana
  selector:
    k8s-app: kibana
