---
apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    name: "kubedash"
    kubernetes.io/cluster-service: "true"
  name: "kubedash"
  namespace: {{namespace}}
spec:
  type: {{svc_type}}
  ports:
    - port: 80
      targetPort: 8289
  selector:
    name: "kubedash"