apiVersion: "v1"
kind: "Service"
metadata:
  name: memcached
  labels: {'k8s-app': 'memcached', 'version': 'v1'}
spec:
  selector: {'k8s-app': 'memcached'}
  ports:
    - name: memcached
      port: 11211
      targetPort: 11211
