---
apiVersion: v1
kind: ReplicationController
metadata:
  name: mongodb
  namespace: {{namespace}}
  labels: {'k8s-app': 'mongodb-mono', 'version': 'v1'}
spec:
  replicas: 1
  selector: {'k8s-app': 'mongodb-mono'}
  template:
    metadata:
      labels: {'k8s-app': 'mongodb-mono', 'version': 'v1'}
    spec:
      containers:
      - name: mongodb
        image: mongo:3.2.0
        resources:
          limits:
            cpu: 1000m
            memory: 4Gi
        volumeMounts: [{'mountPath': '/data/db', 'name': 'mongodb'}]
        ports: [{'protocol': 'TCP', 'containerPort': 27017, 'name': 'mongodb'}]
      volumes: [{'hostPath': {'path': '/containers/rc/{{namespace}}/mongodb-mono/rootfs/data/db'}, 'name': 'mongodb'}]
