---
apiVersion: "v1"
kind: "Service"
metadata:
  name: mongodb
  namespace: {{namespace}}
  labels: {'k8s-app': 'mongodb-mono', 'version': 'v1'}
spec:
  selector: {'k8s-app': 'mongodb-mono'}
  type: NodePort
  ports: [{'protocol': 'TCP', 'targetPort': 27017, 'name': 'mongodb', 'port': 27017}]
