apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ghost
spec:
  backend:
    serviceName: osmbackend
    servicePort: 3000
  tls:
    - secretName: "ghost-tls"
      hosts:
        - "{{ghost_host}}"
        - "example.ott.arkena.com"
