apiVersion: v1
kind: Service
metadata:
  name: monitoring-grafana
  namespace: {{namespace}}
  labels: 
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "Grafana"
spec:
  # On production clusters, consider setting up auth for grafana, and
  # exposing Grafana either using a LoadBalancer or a public IP.
  type: {{svc_type}}
  ports: 
    - port: 80
      targetPort: 3000
  selector: 
    k8s-app: influxGrafana