apiVersion: "v1"
kind: "Service"
metadata:
  name: kubedns
  labels: {
    "k8s-app": "kubedns",
    "kubernetes.io/cluster-service": "true",
}
spec:
  selector: {
    "k8s-app": "kubedns"
}
  clusterIP:  {{cluster_ip}}
  ports:
  - name: dns
    port: 53
    protocol: UDP
  - name: dns-tcp
    port: 53
    protocol: TCP
