---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: weavescope
    weavescope-component: weavescope-app
  name: weavescope-app
spec:
  ports:
    - name: app
      port: 80
      targetPort: 4040
      protocol: TCP
  type: {{svc_type}}
  selector:
    app: weavescope
    weavescope-component: weavescope-app
