---
apiVersion: "v1"
kind: "Service"
metadata:
  name: rocketchat
  labels: {'k8s-app': 'rocketchat'}
  namespace: {{namespace}}
spec:
  selector: {'k8s-app': 'rocketchat'}
  type: NodePort
  ports: [{'protocol': 'TCP', 'targetPort': 3000, 'name': 'rocketchat', 'port': 3000}]
